#Numpy for Data Science

In [0]:
#Importing the library, of course installing it is just as easy
import numpy as np

**Creating an array**

In [0]:
data_list = [13, 17, 97, 99]

In [5]:
np.array(data_list)

array([13, 17, 97, 99])

**Built-in methods of generating arrays**

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
 np.linspace(0,9,3)

array([0. , 4.5, 9. ])

Identity Matrix 

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generating random numbers in the array

In [12]:
np.random.rand(8)

array([0.30323644, 0.94647805, 0.58199863, 0.14591895, 0.26682055,
       0.05088413, 0.05045287, 0.02809326])

In [14]:
#this will create an array from standard normal distribution set of numbers between 0 
#and 1
np.random.randn(4,3)

array([[-0.58020301,  0.62948513,  0.02945464],
       [ 1.83126877,  0.10441727,  1.50158312],
       [ 1.45258569, -0.75601964,  2.52933459],
       [-0.10301313,  0.17256783, -0.99984117]])

In [15]:
np.random.randint(1,50.1)

39

In [0]:
 example1 = np.arange(15)

In [0]:
example2 = np.random.randint(0,45,10)

In [35]:
example1.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
example2.shape

(10,)

In [26]:
example2.dtype 

dtype('int64')

#Array Indexing & Selection

In [0]:
example3 = np.arange(0,12)

In [30]:
example3[:5]

array([0, 1, 2, 3, 4])

In [29]:
example3[2:5]

array([2, 3, 4])

In [0]:
greater6 = example1 > 6

In [39]:
example1[example1>6]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
ex_arr = np.arange(50).reshape(5,10)

# Numpy Operations

In [45]:
 example2 *2

array([ 6, 14, 88, 10, 20, 30,  4, 12, 54, 32])

# Numpy Exercises